<?php

/**
 * @file
 * Paragraph columns module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function colm_1022_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'colm_1022/columns';
}

/**
 * Implements hook_theme().
 */
function colm_1022_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__columns' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__text' => [
      'base hook' => 'paragraph',
    ],
  ];
}